import { CLASSES, EX, MARKETS, NEVER, PLAN, TYPES } from "./data";

export const has = (need, stack) => !need || need.split("+").every((n) => stack[n]);

export function visibleStages(S) {
  return PLAN[S.type]
    .map((st) => ({ ...st, rows: st.rows.filter((r) => has(r.need, S.stack)) }))
    .filter((st) => has(st.need, S.stack) && st.rows.length);
}

export function counts(S) {
  const c = { safe: 0, gated: 0, hash: 0, never: NEVER[S.type].length };
  visibleStages(S).forEach((st) => st.rows.forEach((r) => r.params.forEach((p) => c[p.cls]++)));
  return c;
}

// A row produces a browser dataLayer push when it isn't auto-collected, server-side or an ad destination.
export const isPush = (r, st) => !r.auto && !r.srv && !st.dest && !st.server;
export const isServer = (r, st) => !st.dest && (r.srv || st.server);

const currency = (S) => MARKETS[S.mkt].currency;

function example(p, S) {
  const v = p.ex !== undefined ? p.ex : EX[p.k];
  if (v === "$CURRENCY") return currency(S);
  if (Array.isArray(v)) return v.map((it) => ({ ...it }));
  return v === undefined ? `<${p.k}>` : v;
}

// Pretty-print a JS object literal with single-quoted strings.
export function lit(v, ind = "") {
  const next = ind + "  ";
  if (Array.isArray(v)) {
    if (!v.length) return "[]";
    return "[\n" + v.map((x) => next + lit(x, next)).join(",\n") + "\n" + ind + "]";
  }
  if (v && typeof v === "object") {
    const keys = Object.keys(v);
    if (!keys.length) return "{}";
    return "{\n" + keys.map((k) => `${next}${/^[a-z_$][\w$]*$/i.test(k) ? k : `'${k}'`}: ${lit(v[k], next)}`).join(",\n") + "\n" + ind + "}";
  }
  if (typeof v === "string") return `'${v.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
  return String(v);
}

// Only safe + gated params go into a browser push. Hash params belong to ad tags; never params never appear.
const pushParams = (r) => r.params.filter((p) => p.cls === "safe" || p.cls === "gated");

export function pushObject(r, S) {
  const obj = { event: r.name };
  const params = pushParams(r);
  if (r.ecom) {
    const ecommerce = {};
    params.forEach((p) => { if (p.top) obj[p.k] = example(p, S); else ecommerce[p.k] = example(p, S); });
    obj.ecommerce = ecommerce;
  } else {
    params.forEach((p) => { obj[p.k] = example(p, S); });
  }
  return obj;
}

export function pushSnippet(r, S) {
  const pre = r.ecom ? "dataLayer.push({ ecommerce: null });  // clear the previous ecommerce object\n" : "";
  return pre + "dataLayer.push(" + lit(pushObject(r, S)) + ");";
}

export function mpSnippet(r, S) {
  const params = {};
  let clientId = EX.client_id, userId = null;
  r.params.forEach((p) => {
    if (p.k === "client_id") clientId = example(p, S);
    else if (p.k === "user_id") userId = example(p, S);
    else if (p.cls === "safe" || p.cls === "gated") params[p.k] = example(p, S);
  });
  const body = { client_id: clientId };
  if (userId) body.user_id = userId;
  body.consent = { ad_user_data: "GRANTED", ad_personalization: "DENIED" };
  body.events = [{ name: r.name, params }];
  return `# Sent from your CRM or backend, never from the browser
POST https://www.google-analytics.com/mp/collect?measurement_id=G-XXXXXXXXXX&api_secret=YOUR_API_SECRET
Content-Type: application/json

${JSON.stringify(body, null, 2)}

# client_id: the GA4 client ID saved with the record when the visitor was on the site.
# consent: the choice the visitor made at that moment, not today's default.
# Keep api_secret on the server.`;
}

export function dataLayerSpec(S) {
  const t = TYPES[S.type];
  const never = NEVER[S.type].map(([k]) => k).join(", ");
  const out = [
    `// dataLayer specification · ${t.label} · ${MARKETS[S.mkt].name}`,
    `// Generated by The Clean Tracking Plan. Example values shown; replace with real values.`,
    `// NEVER push: ${never}`,
    ``,
    `window.dataLayer = window.dataLayer || [];`,
  ];
  visibleStages(S).forEach((st) => {
    const rows = st.rows.filter((r) => isPush(r, st));
    if (!rows.length) return;
    out.push("", `// ── ${st.stage} ${"─".repeat(Math.max(4, 60 - st.stage.length))}`);
    rows.forEach((r) => {
      out.push("", `// ${r.name}: ${r.when}`);
      out.push(pushSnippet(r, S));
    });
  });
  const autos = visibleStages(S).flatMap((st) => st.rows.filter((r) => r.auto).map((r) => r.name));
  if (autos.length) out.push("", `// Collected automatically by GA4 enhanced measurement, no push needed:`, `//   ${autos.join(", ")}`);
  return out.join("\n");
}

export function conversionRow(S) {
  for (const st of visibleStages(S)) for (const r of st.rows) if (r.conv) return r;
  return null;
}

export function conversionCode(S) {
  const r = conversionRow(S);
  if (!r) return "// No conversion event for this setup.";
  const fn = "track" + r.name.split("_").map((w) => w[0].toUpperCase() + w.slice(1)).join("");
  const params = pushParams(r);
  const val = (p) => {
    if (p.k === "request_id") return "requestId";
    if (p.k === "currency") return `'${currency(S)}'`;
    if (p.k === "items") return "data.items.map(i => ({ item_id: i.id, item_name: i.name, price: i.price, quantity: i.qty }))";
    return `data.${p.k.replace(/_([a-z])/g, (_, c) => c.toUpperCase())}`;
  };
  const line = (p, ind) => `${ind}${p.k}: ${val(p)},${p.note ? `  // ${p.note}` : ""}`;
  const usesReq = params.some((p) => p.k === "request_id");
  const body = r.ecom
    ? [
        ...params.filter((p) => p.top).map((p) => line(p, "    ")),
        "    ecommerce: {",
        ...params.filter((p) => !p.top).map((p) => line(p, "      ")),
        "    }",
      ]
    : params.map((p) => line(p, "    "));
  const dedupeKey = r.dedupe || (usesReq ? "request_id" : null);
  const dedupeExpr = dedupeKey === "request_id" ? "requestId" : dedupeKey ? val({ k: dedupeKey }) : null;
  const never = NEVER[S.type].map(([k]) => k).join(", ");
  return `// Fire after the server confirms it, not on button click
async function ${fn}(data, adUserDataGranted) {
${usesReq ? `  const requestId = crypto.randomUUID();   // also save this on the record in your CRM\n` : ""}${r.ecom ? "  dataLayer.push({ ecommerce: null });\n" : ""}
  const payload = {
    event: '${r.name}',
${body.join("\n").replace(/,(\s*\/\/[^\n]*)?$/, "$1")}
    // NEVER push: ${never}
  };
${S.stack.ads ? `
  // Enhanced conversions: hashed, and only with ad_user_data consent
  if (adUserDataGranted && data.email) {
    payload.user_data = {
      sha256_email_address: await sha256(normalizeEmailGoogle(data.email)),${S.type === "publisher" || S.type === "saas" ? "" : `
      ...(data.phone && { sha256_phone_number: await sha256(normalizePhoneGoogle(data.phone)) })`}
    };
  }   // In GTM, map these through a User-Provided Data variable
` : ""}${S.stack.meta && dedupeExpr ? `
  payload.event_id = ${dedupeExpr};   // same ID on Meta Pixel + Conversions API
` : ""}${dedupeKey && dedupeKey !== "request_id" ? `
  // Guard against refreshes of the confirmation page
  const key = 'tracked_' + ${dedupeExpr};
  if (sessionStorage.getItem(key)) return;
  sessionStorage.setItem(key, '1');
` : ""}
  dataLayer.push(payload);
}`;
}

export function consentCode(S) {
  const head = `window.dataLayer = window.dataLayer || [];\nfunction gtag(){ dataLayer.push(arguments); }\n`;
  if (S.mkt === "eu") return head + `
// EEA / UK: everything off until the visitor opts in
gtag('consent', 'default', {
  analytics_storage: 'denied',
  ad_storage: 'denied',
  ad_user_data: 'denied',
  ad_personalization: 'denied',
  wait_for_update: 500   // ms to wait for the banner before tags fire
});
gtag('set', 'ads_data_redaction', true);   // strip ad click IDs while ad_storage is denied

// Call from your banner when the visitor chooses
function onConsentChoice(c) {
  gtag('consent', 'update', {
    analytics_storage:  c.analytics ? 'granted' : 'denied',
    ad_storage:         c.marketing ? 'granted' : 'denied',
    ad_user_data:       c.marketing ? 'granted' : 'denied',
    ad_personalization: c.marketing ? 'granted' : 'denied'
  });
}`;
  const quebec = S.mkt === "ca" ? `
// Quebec (Law 25): off by default for CA-QC only
gtag('consent', 'default', {
  analytics_storage: 'denied', ad_storage: 'denied',
  ad_user_data: 'denied', ad_personalization: 'denied',
  region: ['CA-QC'],
  wait_for_update: 500
});
` : "";
  return head + quebec + `
// ${MARKETS[S.mkt].name}: granted with notice, visitor can opt out
gtag('consent', 'default', {
  analytics_storage: 'granted',
  ad_storage: 'granted',
  ad_user_data: 'granted',
  ad_personalization: 'granted'
});

// Call from your "Do not sell or share" link or banner
function optOutOfAds() {
  gtag('consent', 'update', {
    ad_user_data: 'denied',
    ad_personalization: 'denied'${S.mkt === "us" ? "" : ",\n    ad_storage: 'denied'"}
  });
}

// Respect the Global Privacy Control browser signal automatically
if (navigator.globalPrivacyControl) optOutOfAds();`;
}

export function hashCode(S) {
  return `// Google: trim, lowercase, and drop dots before @ for gmail.com / googlemail.com
function normalizeEmailGoogle(email) {
  const e = email.trim().toLowerCase();
  const [user, domain] = e.split('@');
  if (domain === 'gmail.com' || domain === 'googlemail.com') {
    return user.replace(/\\./g, '') + '@' + domain;
  }
  return e;
}

// Google: E.164 format, e.g. +14155550132. Expects the country code to be present;
// add it server-side from the customer's country if your form doesn't collect it.
function normalizePhoneGoogle(phone) {
  const digits = phone.replace(/\\D/g, '').replace(/^00/, '');
  return '+' + digits;
}
${S.stack.meta ? `
// Meta: trim + lowercase only (no dot removal)
function normalizeEmailMeta(email) { return email.trim().toLowerCase(); }

// Meta: digits only, country code included, no "+"
function normalizePhoneMeta(phone) { return phone.replace(/\\D/g, '').replace(/^00/, ''); }
` : ""}
// SHA-256, hex output. Runs in the browser; the raw value never leaves it.
async function sha256(text) {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
  return [...new Uint8Array(buf)].map(b => b.toString(16).padStart(2, '0')).join('');
}`;
}

export function gtmSetup(S) {
  const vars = new Map();
  const triggers = [];
  visibleStages(S).forEach((st) => st.rows.forEach((r) => {
    if (!isPush(r, st)) return;
    triggers.push(r.name);
    pushParams(r).forEach((p) => {
      const path = r.ecom && !p.top ? `ecommerce.${p.k}` : p.k;
      if (!vars.has(path)) vars.set(path, p.cls);
    });
  }));
  const pad = (s, n) => s + " ".repeat(Math.max(1, n - s.length));
  const w = Math.max(...[...vars.keys()].map((k) => k.length), 10) + 8;
  return `# GTM setup · ${TYPES[S.type].label}

## Data Layer Variables (Version 2)
${[...vars.entries()].map(([k, cls]) => `${pad("DLV - " + k, w)}${pad(k, w - 6)}${CLASSES[cls].label}`).join("\n")}

## Triggers (Custom Event)
${triggers.map((t) => `CE - ${t}`).join("\n")}

## Tags
GA4 Configuration (Google tag)   fires on Initialization - All Pages
${triggers.map((t) => `GA4 Event - ${t}`).join("\n")}
${S.stack.ads ? `Google Ads Conversion - ${conversionRow(S)?.name || "conversion"}   with User-Provided Data variable\nConversion Linker                fires on All Pages\n` : ""}${S.stack.meta ? `Meta Pixel                       fires only when marketing consent is granted\n` : ""}
## Rules
- Turn on "Consent Overview" in the container and set built-in consent checks on every tag.
- Never create Form Text, Click Text or Form Element variables on pages with forms.
- Ecommerce events: tick "Send Ecommerce data" in the GA4 event tag (Data Layer source).`;
}

export function codeTabs(S) {
  const tabs = [
    { n: "dataLayer spec", f: "datalayer-spec.js", g: dataLayerSpec },
    { n: "Conversion event", f: `track-${(conversionRow(S)?.name || "conversion").replace(/_/g, "-")}.js`, g: conversionCode },
    { n: "Consent defaults", f: "consent.js", g: consentCode },
  ];
  if (S.stack.ads || S.stack.meta) tabs.push({ n: "Hash helpers", f: "hash.js", g: hashCode });
  const srv = visibleStages(S).flatMap((st) => st.rows.filter((r) => isServer(r, st)))[0];
  if (srv) tabs.push({ n: "Server event", f: "measurement-protocol.http", g: (s) => mpSnippet(srv, s) });
  tabs.push({ n: "GTM setup", f: "gtm-setup.md", g: gtmSetup });
  return tabs;
}

// ── exports
export function planCSV(S) {
  const q = (v) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  const strip = (h) => (h || "").replace(/<[^>]+>/g, "");
  const rows = [["stage", "event", "where", "parameter", "class", "example", "param_note", "consent", "event_note"]];
  visibleStages(S).forEach((st) => st.rows.forEach((r) => {
    const where = st.dest ? "ad platform" : isServer(r, st) ? "server (Measurement Protocol)" : r.auto ? "browser (auto)" : "browser (dataLayer)";
    r.params.forEach((p) => {
      const ex = p.cls === "hash" ? "sha256(…)" : example(p, S);
      rows.push([st.stage, r.name, where, p.k, CLASSES[p.cls].label, typeof ex === "object" ? JSON.stringify(ex) : ex, p.note, r.consent.join(" + "), strip(r.note)]);
    });
  }));
  NEVER[S.type].forEach(([k, why]) => rows.push(["Never collect", "", "nowhere", k, CLASSES.never.label, "", why, "", ""]));
  return rows.map((r) => r.map(q).join(",")).join("\r\n");
}

export function planJSON(S) {
  return JSON.stringify({
    generator: "The Clean Tracking Plan · meghakarnwal",
    site_type: S.type, market: S.mkt, currency: currency(S),
    stack: Object.keys(S.stack).filter((k) => S.stack[k]),
    stages: visibleStages(S).map((st) => ({
      stage: st.stage,
      events: st.rows.map((r) => ({
        name: r.name,
        where: st.dest ? "ad_platform" : isServer(r, st) ? "server" : r.auto ? "auto" : "dataLayer",
        when: r.when,
        consent: r.consent,
        params: r.params.map((p) => ({ key: p.k, class: p.cls, note: p.note || undefined })),
        ...(isPush(r, st) ? { dataLayer: pushObject(r, S) } : {}),
      })),
    })),
    never_collect: NEVER[S.type].map(([key, why]) => ({ key, why })),
  }, null, 2);
}
