// robots.txt parsing and matching (RFC 9309): groups by user-agent, the most specific
// agent group wins, longest matching path wins, Allow wins a tie. Supports * and $.
import { BOTS, PRESETS } from "./bots";

export function parseRobots(text) {
  const groups = [];
  let cur = null, lastWasAgent = false;
  const sitemaps = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/#.*/, "").trim();
    if (!line) continue;
    const m = line.match(/^([A-Za-z-]+)\s*:\s*(.*)$/);
    if (!m) continue;
    const key = m[1].toLowerCase(), val = m[2].trim();
    if (key === "user-agent") {
      if (!cur || !lastWasAgent) { cur = { agents: [], rules: [], crawlDelay: null }; groups.push(cur); }
      cur.agents.push(val.toLowerCase());
      lastWasAgent = true;
      continue;
    }
    lastWasAgent = false;
    if (key === "sitemap") { sitemaps.push(val); continue; }
    if (!cur) continue;
    if (key === "allow" || key === "disallow") cur.rules.push({ type: key, path: val });
    if (key === "crawl-delay") cur.crawlDelay = val;
  }
  return { groups, sitemaps };
}

function groupFor(groups, token) {
  const t = token.toLowerCase();
  // Exact token match first (RFC 9309 matches the product token case-insensitively), then "*".
  const exact = groups.filter((g) => g.agents.some((a) => a === t));
  if (exact.length) return { group: { agents: exact.flatMap((g) => g.agents), rules: exact.flatMap((g) => g.rules), crawlDelay: exact.find((g) => g.crawlDelay)?.crawlDelay ?? null }, matched: token };
  const star = groups.filter((g) => g.agents.includes("*"));
  if (star.length) return { group: { agents: ["*"], rules: star.flatMap((g) => g.rules), crawlDelay: star.find((g) => g.crawlDelay)?.crawlDelay ?? null }, matched: "*" };
  return { group: null, matched: null };
}

function patternToRe(p) {
  const anchored = p.endsWith("$");
  const body = (anchored ? p.slice(0, -1) : p).replace(/[.+?^{}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*");
  return new RegExp("^" + body + (anchored ? "$" : ""));
}

export function allowed(groups, token, path = "/") {
  const { group, matched } = groupFor(groups, token);
  if (!group) return { allowed: true, via: "no rule (allowed)", rule: null, matched: null, crawlDelay: null };
  let best = null;
  for (const r of group.rules) {
    if (r.type === "disallow" && r.path === "") continue; // "Disallow:" (empty) allows everything
    if (!patternToRe(r.path).test(path)) continue;
    const len = r.path.replace(/\$$/, "").length;
    if (!best || len > best.len || (len === best.len && r.type === "allow")) best = { ...r, len };
  }
  const ok = !best || best.type === "allow";
  return { allowed: ok, via: matched === "*" ? "rules for all bots (*)" : `rules for ${matched}`, rule: best ? `${best.type === "allow" ? "Allow" : "Disallow"}: ${best.path}` : null, matched, crawlDelay: group.crawlDelay };
}

// Corrected robots.txt for an intent: keeps every non-AI group as it is and rewrites the AI ones.
export function generateRobots(text, presetKey) {
  const preset = PRESETS[presetKey];
  const aiTokens = new Set(BOTS.map((b) => b.token.toLowerCase()));
  const keepSearchEngines = new Set(["googlebot", "bingbot"]);
  const lines = text.split(/\r?\n/);
  // Drop existing groups that only name AI bots (they get rewritten below).
  const out = [];
  let i = 0;
  while (i < lines.length) {
    const agentLines = [];
    while (i < lines.length && /^\s*user-agent\s*:/i.test(lines[i])) agentLines.push(lines[i++]);
    if (agentLines.length) {
      const agents = agentLines.map((l) => l.split(":").slice(1).join(":").trim().toLowerCase());
      const body = [];
      while (i < lines.length && !/^\s*user-agent\s*:/i.test(lines[i])) body.push(lines[i++]);
      const onlyAi = agents.every((a) => aiTokens.has(a) && !keepSearchEngines.has(a));
      if (!onlyAi) out.push(...agentLines, ...body);
      continue;
    }
    out.push(lines[i++]);
  }
  const groupsByAction = { allow: [], disallow: [] };
  for (const b of BOTS) {
    if (keepSearchEngines.has(b.token.toLowerCase())) continue; // never touch Googlebot / Bingbot here
    groupsByAction[preset.rule[b.purpose]].push(b);
  }
  const block = [`# ── AI crawlers: "${preset.label}" (generated by AI Crawler Gate) ──`];
  if (groupsByAction.disallow.length) block.push(...groupsByAction.disallow.map((b) => `User-agent: ${b.token}`), "Disallow: /", "");
  if (groupsByAction.allow.length) block.push(...groupsByAction.allow.map((b) => `User-agent: ${b.token}`), "Allow: /", "");
  const body = out.join("\n").replace(/\n{3,}/g, "\n\n").trim();
  return `${body ? body + "\n\n" : ""}${block.join("\n").trim()}\n`;
}
